name: 'devtree'

services:
  mongo:
    image: mongo:5
    restart: always
    environment:
      - MONGODB_DATABASE=devtree
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db